// example/react-theme-switch-demo/src/views/home/index.jsx
import React from "react";
import { message, Menu, Dropdown } from "antd";
import { DownOutlined } from "@ant-design/icons";
import Table from "./table";
import Checkbox from "./checkbox";
import Radio from "./radio";
import Button from "./button";
import Collapse from "./collapse";
import SwitcherThemeTool from "theme-switcher-tool";
import {
    addGithubComment,
    setGithubCommentTheme
} from "../../utils/github-comment";

const themes = [
    {
        themeName: "theme-black",
        selected: false
    },
    {
        themeName: "theme-blue",
        selected: false
    },
    {
        themeName: "theme-orange",
        selected: false
    },
    {
        themeName: "theme-red",
        selected: false
    }
];

// get theme list by theme-generator-webpack-plugin
const themeList = window.generator_webpack_plugin_theme_vars.map(item => {
    return {
        themeName: item.key,
        themePath: item.themePath
    };
});

// init theme-switcher-tool
const themeSwitcherTool = SwitcherThemeTool({
    themeList: themeList,
    styleLinkId: "theme_creator_cli_style_id",
    useStorage: true,
    storageKey: "theme_switcher_tool_theme"
});

export default class Home extends React.Component {
    state = {
        themes: themes
    };

    componentDidMount() {
        // set default theme
        const currentTheme = themeSwitcherTool.getCurrentTheme();
        if (currentTheme) {
            this.changeTheme(currentTheme);
        }

        // add comments plugin
        addGithubComment("#utterances-github-comments-plugin");
    }

    // change theme
    changeTheme(themeName) {
        this.setState({
            themes: this.state.themes.slice().map(item => {
                item.selected = themeName === item.themeName;
                return item;
            })
        });

        // loading
        let msgComp = message.loading("theme loading...");

        themeSwitcherTool
            .switcher({
                themeName: themeName
            })
            .then(() => {
                // hide loading
                setTimeout(msgComp);

                // set github comments theme
                setGithubCommentTheme(
                    "#utterances-github-comments-plugin iframe",
                    themeName
                );
            });
    }

    render() {
        const menu = (
            <Menu>
                <Menu.Item>
                    <a
                        target="_blank"
                        rel="noopener noreferrer"
                        href="https://github.com/huangshuwei/theme-generator-webpack-plugin"
                    >
                        theme-generator-webpack-plugin
                    </a>
                </Menu.Item>
                <Menu.Item>
                    <a
                        target="_blank"
                        rel="noopener noreferrer"
                        href="https://github.com/huangshuwei/theme-switcher-tool"
                    >
                        theme-switcher-tool
                    </a>
                </Menu.Item>
            </Menu>
        );

        return (
            <div className="home">
                <div className="home-top-bar">
                    <div className="left">React Ant.Design UI Example</div>
                    <div className="right">
                        <div className="tool">
                            {this.state.themes.map((theme, index) => {
                                return (
                                    <span
                                        key={index}
                                        onClick={() =>
                                            this.changeTheme(theme.themeName)
                                        }
                                        className={`${theme.themeName} color-item`}
                                    >
                                        {theme.selected && (
                                            <i className="iconfont icon-check" />
                                        )}
                                    </span>
                                );
                            })}
                        </div>
                        <div className="link-info">
                            <Dropdown overlay={menu} trigger="click">
                                <i className="iconfont icon-GitHub">
                                    &nbsp;&nbsp;
                                    <DownOutlined />
                                </i>
                            </Dropdown>
                        </div>
                    </div>
                </div>
                <div className="home-content">
                    <div className="content-item">
                        <div className="content-item-block">
                            <span className="icon" />
                            <span className="title">Table</span>
                        </div>
                        <Table />
                    </div>
                    <div className="content-item">
                        <div className="content-item-block">
                            <span className="icon" />
                            <span className="title">Checkbox</span>
                        </div>
                        <Checkbox />
                    </div>
                    <div className="content-item">
                        <div className="content-item-block">
                            <span className="icon" />
                            <span className="title">Radio</span>
                        </div>
                        <Radio />
                    </div>
                    <div className="content-item">
                        <div className="content-item-block">
                            <span className="icon" />
                            <span className="title">Button</span>
                        </div>
                        <Button />
                    </div>
                    <div className="content-item">
                        <div className="content-item-block">
                            <span className="icon" />
                            <span className="title">Collapse</span>
                        </div>
                        <Collapse />
                    </div>
                    <div className="content-item">
                        <div className="content-item-block">
                            <span className="icon" />
                            <span className="title">
                                Github Comments(need proxy)
                            </span>
                        </div>
                        {/* add github comments */}
                        <div id="utterances-github-comments-plugin"></div>
                    </div>
                </div>
            </div>
        );
    }
}

// example/vue-theme-switch-demo/src/views/home/index.vue
<template>
    <div class="home">
        <div class="home-top-bar">
            <div class="left">Vue Element UI Example</div>
            <div class="right">
                <div class="tool">
                    <span
                        @click="changeTheme(item)"
                        :class="[item.themeName, 'color-item']"
                        :key="item.themeName"
                        v-for="item in themes"
                    >
                        <i v-if="item.selected" class="iconfont icon-check" />
                    </span>
                </div>
                <div class="link-info">
                    <el-dropdown trigger="click">
                        <span class="el-dropdown-link">
                            <i class="iconfont icon-GitHub" />
                            <i class="el-icon-arrow-down el-icon--right" />
                        </span>
                        <el-dropdown-menu slot="dropdown">
                            <el-dropdown-item>
                                <a
                                    class="link-refernece"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    href="https://github.com/huangshuwei/theme-generator-webpack-plugin"
                                >
                                    theme-generator-webpack-plugin
                                </a>
                            </el-dropdown-item>
                            <el-dropdown-item>
                                <a
                                    class="link-refernece"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    href="https://github.com/huangshuwei/theme-switcher-tool"
                                >
                                    theme-switcher-tool
                                </a>
                            </el-dropdown-item>
                        </el-dropdown-menu>
                    </el-dropdown>
                </div>
            </div>
        </div>
        <div class="home-content">
            <div class="content-item">
                <div class="content-item-block">
                    <span class="icon" />
                    <span class="title">Table</span>
                </div>
                <Table />
            </div>
        </div>
    </div>
</template>
<script>
import SwitcherThemeTool from "theme-switcher-tool";
import "./index.scss";
import Table from "./table";

// get theme list by theme-generator-webpack-plugin
const themeList = window.generator_webpack_plugin_theme_vars.map(item => {
    return {
        themeName: item.key,
        themePath: item.themePath
    };
});

// init theme-switcher-tool
const themeSwitcherTool = SwitcherThemeTool({
    themeList: themeList,
    styleLinkId: "theme_creator_cli_style_id",
    useStorage: true,
    storageKey: "theme_switcher_tool_theme"
});

export default {
    components: { Table },
    data() {
        return {
            themes: [
                {
                    themeName: "theme-black",
                    selected: false
                },
                {
                    themeName: "theme-blue",
                    selected: false
                },
                {
                    themeName: "theme-orange",
                    selected: false
                },
                {
                    themeName: "theme-red",
                    selected: false
                }
            ]
        };
    },
    methods: {
        changeTheme(item) {
            if (item.selected) {
                return false;
            }

            this.themes = this.themes.map(x => {
                x.selected = item.themeName === x.themeName;
                return x;
            });
        }
    }
};
</script>
